import { useEffect, useState } from 'react'
import { Check, Clock3, MapPin, RefreshCcw, ShieldCheck, X } from 'lucide-react'
import { fetchAdminContributions, fetchAdminSummary, moderateContribution } from '../lib/api'
import type { AdminSummary, Contribution } from '../types'

export function AdminReview(){
 const [summary,setSummary]=useState<AdminSummary|null>(null),[rows,setRows]=useState<Contribution[]>([]),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[selected,setSelected]=useState<Contribution|null>(null),[error,setError]=useState('')
 async function load(){setBusy(true);setError('');try{const [s,r]=await Promise.all([fetchAdminSummary(),fetchAdminContributions('pending')]);setSummary(s);setRows(r)}catch(e){setError(e instanceof Error?e.message:'Could not load moderation queue.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 async function moderate(status:'approved'|'rejected'){if(!selected)return;setBusy(true);try{await moderateContribution(selected.id,status,note);setSelected(null);setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Moderation failed.')}finally{setBusy(false)}}
 return <section className="section-stack"><div className="section-heading"><div><span className="eyebrow">AUTHORITY WORKSPACE</span><h2>Moderation & verification queue</h2><p>Only backend-authorized admin claims can approve or reject submissions.</p></div><button className="outline-button" onClick={load}><RefreshCcw size={15} className={busy?'spin':''}/> Refresh</button></div>{summary&&<div className="mini-stat-row"><div><span>Pending</span><strong>{summary.pending}</strong></div><div><span>Approved 24h</span><strong>{summary.approved24h}</strong></div><div><span>Rejected 24h</span><strong>{summary.rejected24h}</strong></div></div>}{error&&<div className="form-error">{error}</div>}<div className="review-grid">{rows.length?rows.map(c=><button className="review-card" key={c.id} onClick={()=>setSelected(c)}><div className="review-top"><span className="review-type">{c.type.replaceAll('_',' ')}</span><span className="pending-badge"><Clock3 size={12}/> Pending</span></div><h3>{c.name}</h3><p>{c.description}</p><div className="review-meta"><span><MapPin size={13}/>{c.lat.toFixed(4)}, {c.lon.toFixed(4)}</span><span>{c.userName}</span></div></button>):<div className="empty-card"><ShieldCheck size={24}/><strong>No pending reports</strong><span>The queue is clear.</span></div>}</div>{selected&&<div className="drawer-backdrop" onMouseDown={()=>setSelected(null)}><aside className="review-drawer" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}><X size={18}/></button><span className="eyebrow">REPORT REVIEW</span><h2>{selected.name}</h2><div className="drawer-badges"><span>{selected.type.replaceAll('_',' ')}</span><span>Google verified contributor</span></div><dl><div><dt>Coordinates</dt><dd>{selected.lat.toFixed(6)}, {selected.lon.toFixed(6)}</dd></div><div><dt>Area</dt><dd>{selected.district||'—'}, {selected.state||'—'}</dd></div><div><dt>Capacity</dt><dd>{selected.capacity.toLocaleString()}</dd></div><div><dt>Submitted</dt><dd>{new Date(selected.createdAt).toLocaleString()}</dd></div></dl><div className="drawer-description"><strong>Observation</strong><p>{selected.description}</p></div><label className="admin-note">Moderation note<textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Why was this approved/rejected?"/></label><div className="moderation-actions"><button className="reject-button" disabled={busy} onClick={()=>moderate('rejected')}><X size={15}/> Reject</button><button className="approve-button" disabled={busy} onClick={()=>moderate('approved')}><Check size={15}/> Approve & publish</button></div></aside></div>}</section>
}
