import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, LocateFixed, MapPin, ShieldCheck, X } from 'lucide-react'
import type { User } from 'firebase/auth'
import type { ContributionType } from '../types'
import { isFirebaseConfigured, loginWithGoogle } from '../lib/firebase'
import { submitContribution } from '../lib/api'

interface Props { user:User|null; selectedLocation:{lat:number;lon:number}|null; onClose:()=>void; onLocationNeeded:()=>void; onSubmitted:()=>void }
const OPTIONS:Array<[ContributionType,string]>= [
 ['relief_centre','Relief / rehabilitation centre'],['shelter','Temporary shelter'],['medical','Medical support point'],['food_water','Food / water availability'],['road_blockage','Road / bridge blockage'],['flood_report','Flood / waterlogging report'],['landslide_report','Landslide report'],['other','Other useful information']]

export function ContributeModal({user,selectedLocation,onClose,onLocationNeeded,onSubmitted}:Props){
 const [type,setType]=useState<ContributionType>('relief_centre'),[name,setName]=useState(''),[description,setDescription]=useState(''),[capacity,setCapacity]=useState('100'),[lat,setLat]=useState(''),[lon,setLon]=useState(''),[state,setState]=useState(''),[district,setDistrict]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false)
 useEffect(()=>{if(selectedLocation){setLat(String(selectedLocation.lat.toFixed(6)));setLon(String(selectedLocation.lon.toFixed(6)))}},[selectedLocation])
 const locationReady=useMemo(()=>Number.isFinite(Number(lat))&&Number.isFinite(Number(lon))&&lat!==''&&lon!=='',[lat,lon])
 const isIndia=locationReady&&Number(lat)>=6&&Number(lat)<=38&&Number(lon)>=68&&Number(lon)<=98
 async function google(){setError('');try{await loginWithGoogle()}catch(e){setError(e instanceof Error?e.message:'Google sign-in failed.')}}
 async function send(e:React.FormEvent){e.preventDefault();setError('');if(!isFirebaseConfigured())return setError('Firebase is not configured. Add the VITE_FIREBASE_* settings first.');if(!user)return setError('Google sign-in is required.');if(!isIndia)return setError('Pick a valid location inside the India monitoring envelope.');if(name.trim().length<3)return setError('Give the reported place a clear name.');if(description.trim().length<12)return setError('Add enough detail for an authority reviewer.');const cap=Math.max(0,Math.min(100000,Number(capacity)||0));setSending(true);try{await submitContribution({type,name:name.trim(),description:description.trim(),lat:Number(lat),lon:Number(lon),capacity:cap,state:state.trim(),district:district.trim()});setSuccess(true);onSubmitted()}catch(e){setError(e instanceof Error?e.message:'Could not submit contribution.')}finally{setSending(false)}}
 return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}><X size={18}/></button>{success?<div className="success-box"><CheckCircle2 size={52}/><h2>Contribution submitted</h2><p>Your report is queued for authority review. Only approved data becomes public.</p><button className="primary-button" onClick={onClose}>Done</button></div>:<><div className="modal-head"><div><span className="eyebrow">COMMUNITY INTELLIGENCE</span><h2>Contribute verified field data</h2><p>Google sign-in is mandatory to reduce spam, duplicate locations and anonymous fabrication.</p></div><div className="security-pill"><ShieldCheck size={15}/> Moderated</div></div>{!user?<div className="auth-gate"><div className="google-circle"><span>G</span></div><div><strong>Link a Google account</strong><span>Your name, UID and provider are recorded with the submission for moderation.</span></div><button className="google-button" onClick={google}>Continue with Google</button>{!isFirebaseConfigured()&&<small>Firebase configuration is required for Google authentication.</small>}</div>:<div className="signed-user"><img src={user.photoURL??''} alt=""/><div><strong>{user.displayName??'Verified contributor'}</strong><span>{user.email??'Google account'}</span></div><b><ShieldCheck size={13}/> Google verified</b></div>}
 <form className="contribute-form" onSubmit={send}><div className="form-grid"><label>Report type<select value={type} onChange={e=>setType(e.target.value as ContributionType)}>{OPTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Community Shelter, road blockage"/></label><label>State<input value={state} onChange={e=>setState(e.target.value)} placeholder="State / UT"/></label><label>District<input value={district} onChange={e=>setDistrict(e.target.value)} placeholder="District"/></label><label>Capacity / count<input type="number" min="0" max="100000" value={capacity} onChange={e=>setCapacity(e.target.value)}/></label><label>Description<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What did you observe? When? What services or constraints exist?"/></label></div>
 <div className="location-box"><div><strong><MapPin size={15}/> Location</strong><span>{locationReady?`${Number(lat).toFixed(6)}, ${Number(lon).toFixed(6)}`:'No location selected'}</span></div><button type="button" className="outline-button" onClick={onLocationNeeded}><LocateFixed size={14}/> Pick on map</button></div>
 <div className="notice"><ShieldCheck size={14}/><span>Submission is created as <b>pending</b>. Authority review checks duplicates, plausibility and source context before public publication.</span></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!user||sending}>{sending?'Submitting…':'Submit for review'}</button></div></form></>}</div></div>
}
